name: "Set Commit Status"
description: "Set GitHub commit status for a stage like BUILD/SCAN/DEPLOY"

inputs:
  context:
    description: "Status context name (e.g., DEV/BUILD, DEV/SCAN, DEV/DEPLOY)"
    required: true
  outcome:
    description: "Step outcome (success/failure/skipped)"
    required: true
  description:
    description: "Human readable prefix (e.g., BUILD, SCAN, DEPLOY)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set commit status
      uses: actions/github-script@v7
      with:
        script: |
          const outcome = '${{ inputs.outcome }}' || 'skipped';
          const ok = outcome === 'success';
          const state = ok ? 'success' : 'failure';

          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state,
            context: '${{ inputs.context }}',
            description: `${{ inputs.description }} ${state.toUpperCase()}`,
            target_url: `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
          });

